# Generated by Django 5.0.7 on 2024-07-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('WorkerID_Int', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('WorkerID', models.CharField(max_length=21)),
                ('Host', models.URLField(max_length=255)),
                ('Port', models.PositiveIntegerField()),
                ('PerformanceScore', models.PositiveIntegerField()),
                ('Status', models.CharField(choices=[('AV', 'Available'), ('WK', 'Working'), ('QT', 'Quitting'), ('DC', 'Disconnected')], max_length=2)),
            ],
        ),
    ]
