# Generated by Django 4.0.6 on 2024-06-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RenderTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskID', models.CharField(max_length=19, unique=True)),
                ('FileServerAddress', models.URLField()),
                ('FileServerPort', models.PositiveIntegerField()),
                ('dataType', models.CharField(choices=[(0, 'SingleFile'), (1, 'MultiFile')], max_length=1)),
                ('outputType', models.CharField(choices=[(0, 'TARGA'), (1, 'IRIS'), (7, 'IRIZ'), (14, 'RAWTGA'), (15, 'AVIRAW'), (16, 'AVIJPEG'), (17, 'PNG'), (20, 'BMP'), (21, 'RADHDR'), (22, 'TIFF'), (23, 'OPENEXR'), (24, 'FFMPEG'), (26, 'CINEON'), (27, 'DPX'), (28, 'MULTILAYER'), (29, 'DDS'), (30, 'JP2'), (31, 'H264'), (32, 'XVID'), (33, 'THEORA'), (34, 'PSD'), (35, 'WEBP'), (36, 'AV1'), (255, 'INVALID')], max_length=1)),
                ('StartFrame', models.PositiveIntegerField()),
                ('EndFrame', models.PositiveIntegerField()),
                ('FrameStep', models.PositiveIntegerField()),
            ],
        ),
    ]
