# Generated by Django 4.0.6 on 2024-07-10 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WorkerManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenderTask',
            fields=[
                ('taskID_Int', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('TaskID', models.CharField(max_length=21, unique=True)),
                ('FileServerAddress', models.URLField()),
                ('FileServerPort', models.PositiveIntegerField()),
                ('dataType', models.CharField(max_length=1)),
                ('outputType', models.CharField(max_length=1)),
                ('StartFrame', models.PositiveIntegerField()),
                ('EndFrame', models.PositiveIntegerField()),
                ('FrameStep', models.PositiveIntegerField()),
                ('stage', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartFrame', models.PositiveIntegerField()),
                ('EndFrame', models.PositiveIntegerField()),
                ('LastestFrame', models.PositiveIntegerField()),
                ('Portion', models.FloatField()),
                ('Task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subtasks', to='TaskScheduler.rendertask')),
                ('Worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkerManager.worker')),
            ],
        ),
    ]
