# Generated by Django 5.0.7 on 2024-07-14 12:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WorkerManager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RenderTask',
            fields=[
                ('TaskID_Int', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('TaskID', models.CharField(max_length=21, unique=True)),
                ('FileServerAddress', models.URLField()),
                ('FileServerPort', models.PositiveIntegerField()),
                ('DataType', models.CharField(choices=[('SINGL', 'SingleFile'), ('MULTI', 'MultiFile')], max_length=5)),
                ('OutputType', models.CharField(choices=[('.rgb', 'Iris'), ('.jpg', 'JPEG'), ('.jp2', 'JPEG 200 J2'), ('.j2c', 'JPEG 200 J2K'), ('.png', 'PNG'), ('.bmp', 'BMP'), ('.tga', 'TARGA'), ('.tga.r', 'TARGA Raw'), ('.cin', 'Cineon'), ('.dpx', 'DPX'), ('.exr', 'OpenEXR'), ('.exr.m', 'OpenEXR Multilayer'), ('.hdr', 'Radiance HDR'), ('.tif', 'TIFF'), ('.webp', 'WebP'), ('.avi.j', 'AVI JPEG'), ('.avi.r', 'AVI RAW'), ('.mpg', 'MPEG-1'), ('.dvd', 'MPEG-2'), ('.mp4', 'MPEG-4'), ('.avi', 'AVI'), ('.mov', 'QuickTime'), ('.dv', 'DV'), ('.flv', 'Flash'), ('.mkv', 'Matroska'), ('.ogv', 'OGG'), ('.webm', 'WebM')], max_length=6, null=True)),
                ('StartFrame', models.PositiveIntegerField(null=True)),
                ('EndFrame', models.PositiveIntegerField(null=True)),
                ('FrameStep', models.PositiveIntegerField(null=True)),
                ('Stage', models.CharField(choices=[('1-UPL', 'Uploading'), ('2-PEN', 'Pending'), ('3-DIS', 'Distributing'), ('4-REN', 'Rendering'), ('5-CON', 'Concatenating'), ('6-FIN', 'Finished'), ('7-EXP', 'Expired')], max_length=5)),
                ('StartedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('FinishedAt', models.DateTimeField(null=True)),
                ('CreatedBy', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('SubtaskIndex', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('StartFrame', models.PositiveIntegerField()),
                ('EndFrame', models.PositiveIntegerField()),
                ('LastestFrame', models.PositiveIntegerField()),
                ('Portion', models.FloatField()),
                ('Stage', models.CharField(choices=[('1-PEN', 'Pending'), ('2-RUN', 'Running'), ('3-FIN', 'Finished'), ('4-ABO', 'Aborted')], default='1-PEN', max_length=5)),
                ('Task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subtasks', to='TaskScheduler.rendertask')),
                ('Worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkerManager.worker')),
            ],
        ),
        migrations.AddConstraint(
            model_name='subtask',
            constraint=models.UniqueConstraint(fields=('SubtaskIndex', 'Task'), name='SubtaskIndex-TaskID-UniqueConstraint'),
        ),
    ]
