# Generated by Django 5.0.6 on 2024-07-13 20:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TaskScheduler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rendertask",
            name="FinishedAt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="rendertask",
            name="StartedAt",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
