# Generated by Django 4.0.6 on 2024-06-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskScheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenderTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskID', models.CharField(max_length=19, unique=True)),
                ('FileServerAddress', models.URLField()),
            ],
        ),
    ]
