# Generated by Django 5.0.7 on 2024-07-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskScheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='LastestFrame',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
