# Generated by Django 5.0.7 on 2024-07-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskScheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendertask',
            name='OutputType',
            field=models.CharField(choices=[('.rgb', 'Iris'), ('.jpg', 'JPEG'), ('.jp2', 'JPEG 200 J2'), ('.j2c', 'JPEG 200 J2K'), ('.tga', 'TARGA'), ('.tga.r', 'TARGA Raw'), ('.cin', 'Cineon'), ('.dpx', 'DPX'), ('.exr', 'OpenEXR'), ('.exr.m', 'OpenEXR Multilayer'), ('.hdr', 'Radiance HDR'), ('.tif', 'TIFF'), ('.webp', 'WebP'), ('.avi.j', 'AVI JPEG'), ('.avi.r', 'AVI RAW'), ('.mpg', 'MPEG-1'), ('.dvd', 'MPEG-2'), ('.mp4', 'MPEG-4'), ('.avi', 'AVI'), ('.mov', 'QuickTime'), ('.dv', 'DV'), ('.flv', 'Flash'), ('.mkv', 'Matroska'), ('.ogv', 'OGG'), ('.webm', 'WebM')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='rendertask',
            name='Stage',
            field=models.CharField(choices=[('1-UPL', 'Uploading'), ('2-PEN', 'Pending'), ('3-DIS', 'Distributing'), ('4-REN', 'Rendering'), ('5-CON', 'Concatenating'), ('6-FIN', 'Finished'), ('7-EXP', 'Expired')], max_length=5),
        ),
    ]
