# Generated by Django 5.0.7 on 2024-07-16 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskScheduler', '0002_alter_subtask_lastestframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='Task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subtask_set', to='TaskScheduler.rendertask'),
        ),
    ]
