# Generated by Django 4.0.6 on 2024-06-24 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskScheduler', '0003_alter_rendertask_datatype_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RenderTaskModel',
        ),
    ]
