# Generated by Django 4.0.6 on 2024-06-24 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskScheduler', '0004_delete_rendertaskmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RenderTask',
        ),
    ]
