# Generated by Django 4.0.6 on 2024-06-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TaskScheduler', '0005_delete_rendertask'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenderTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskID', models.CharField(max_length=19, unique=True)),
                ('FileServerAddress', models.URLField()),
                ('FileServerPort', models.PositiveIntegerField()),
                ('dataType', models.CharField(max_length=1)),
                ('outputType', models.CharField(max_length=1)),
                ('StartFrame', models.PositiveIntegerField()),
                ('EndFrame', models.PositiveIntegerField()),
                ('FrameStep', models.PositiveIntegerField()),
            ],
        ),
    ]
