# Generated by Django 4.0.6 on 2024-07-10 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkerManager', '0001_initial'),
        ('TaskScheduler', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendertask',
            name='TaskID',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartFrame', models.PositiveIntegerField()),
                ('EndFrame', models.PositiveIntegerField()),
                ('FramesFinished', models.PositiveIntegerField()),
                ('Portion', models.FloatField()),
                ('Task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subtasks', to='TaskScheduler.rendertask')),
                ('Worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkerManager.worker')),
            ],
        ),
    ]
